modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Suiranoil/SkinRestorer/issues"

[[mods]]
modId = "skinrestorer"
version = "2.3.1+1.21-neoforge"
displayName = "SkinRestorer"
authors = "Lionarius"
logoFile = "assets/skinrestorer/icon.png"
displayURL = "https://modrinth.com/mod/skinrestorer"
description = "A server-side mod for managing skins."

[[mixins]]
config = "skinrestorer.mixins.json"

[[dependencies.skinrestorer]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skinrestorer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21, 1.21.4]"
ordering = "NONE"
side = "BOTH"
